export const toolColors: Record<string, string> = {
    claude: '#c4a0ff',
    codex: '#66e088',
    gemini: '#7fd4ff',
    copilot: '#66b3ff',
    opencode: '#bc8cff',
    pi: '#ff7b29',
}

export const statusConfig: Record<string, { color: string; label: string; icon?: string; bg?: string }> = {
    active: { color: 'var(--success)', label: 'Running', bg: 'color-mix(in oklch, var(--success) 8%, transparent)' },
    waiting: { color: 'var(--warning)', label: 'Waiting', icon: '●', bg: 'color-mix(in oklch, var(--warning) 8%, transparent)' },
    error: { color: 'var(--destructive)', label: 'Error', icon: '!', bg: 'color-mix(in oklch, var(--destructive) 8%, transparent)' },
    stuck: { color: 'oklch(0.70 0.18 50)', label: 'Stuck', icon: '◴', bg: 'color-mix(in oklch, oklch(0.70 0.18 50) 10%, transparent)' },
    completed: { color: 'var(--success)', label: 'Completed', icon: '✓', bg: 'color-mix(in oklch, var(--success) 8%, transparent)' },
}


import type { SessionState } from './lib/sessionState'

export interface SignalTreatment {
    dot: string
    text: string
    pulse: boolean
    hollow: boolean
}

export const signalTreatment: Record<SessionState, SignalTreatment> = {
    needs_you: { dot: 'var(--warning)', text: 'var(--warning)', pulse: true, hollow: false },
    working: { dot: 'var(--success)', text: 'var(--body-text)', pulse: false, hollow: false },
    idle: { dot: 'var(--mute)', text: 'var(--mute)', pulse: false, hollow: true },
    offline: { dot: 'var(--stone)', text: 'var(--mute)', pulse: false, hollow: true },
}

export interface ThemePreset {
    name: string
    label: string
    cssVars: Record<string, string>
    xterm: {
        background: string
        foreground: string
        cursor: string
        cursorAccent: string
        selectionBackground: string
        black: string
        red: string
        green: string
        yellow: string
        blue: string
        magenta: string
        cyan: string
        white: string
        brightBlack: string
        brightRed: string
        brightGreen: string
        brightYellow: string
        brightBlue: string
        brightMagenta: string
        brightCyan: string
        brightWhite: string
    }
}

export const themePresets: Record<string, ThemePreset> = {
    'raycast': {
        name: 'raycast',
        label: 'Raycast',
        cssVars: {
            // Design tokens (Raycast palette)
            '--canvas': '#07080a',
            '--surface': '#0d0d0d',
            '--surface-elevated': '#101111',
            '--surface-card': '#121212',
            '--hairline': '#242728',
            '--hairline-soft': 'rgba(255,255,255,0.08)',
            '--hairline-strong': 'rgba(255,255,255,0.16)',
            '--ink': '#f4f4f6',
            '--body-text': '#cdcdcd',
            '--mute': '#9c9c9d',
            '--ash': '#6a6b6c',
            '--stone': '#434345',
            '--on-dark': '#ffffff',
            '--on-dark-mute': 'rgba(255,255,255,0.72)',
            '--accent-blue': '#57c1ff',
            '--accent-blue-soft': 'rgba(87,193,255,0.15)',
            '--accent-red': '#ff6161',
            '--accent-red-soft': 'rgba(255,97,97,0.15)',
            '--accent-green': '#59d499',
            '--accent-green-soft': 'rgba(89,212,153,0.15)',
            '--accent-yellow': '#ffc533',
            '--accent-yellow-soft': 'rgba(255,197,51,0.15)',
            '--hero-stripe-start': '#ff5757',
            '--hero-stripe-end': '#a1131a',
            // Shadcn CSS variable mappings
            '--background': 'var(--canvas)',
            '--foreground': 'var(--ink)',
            '--card': 'var(--surface)',
            '--card-foreground': 'var(--ink)',
            '--popover': 'var(--surface-elevated)',
            '--popover-foreground': 'var(--ink)',
            '--primary': '#ffffff',
            '--primary-foreground': '#000000',
            '--secondary': 'transparent',
            '--secondary-foreground': 'var(--on-dark)',
            '--muted': 'var(--surface-elevated)',
            '--muted-foreground': 'var(--mute)',
            '--accent': 'var(--on-dark)',
            '--accent-foreground': '#000000',
            '--destructive': 'var(--accent-red)',
            '--destructive-foreground': 'var(--on-dark)',
            '--border': 'var(--hairline)',
            '--input': 'var(--surface-elevated)',
            '--ring': 'var(--on-dark)',
            '--success': 'var(--accent-green)',
            '--warning': 'var(--accent-yellow)',
            '--sidebar': 'var(--canvas)',
            '--sidebar-foreground': 'var(--ink)',
            '--sidebar-primary': 'var(--on-dark)',
            '--sidebar-primary-foreground': '#000000',
            '--sidebar-accent': 'var(--surface-elevated)',
            '--sidebar-accent-foreground': 'var(--on-dark)',
            '--sidebar-border': 'var(--hairline)',
            '--sidebar-ring': 'var(--on-dark)',
            '--chart-primary': 'var(--on-dark)',
            '--chart-secondary': 'var(--accent-blue)',
        },
        xterm: {
            background: '#07080a',
            foreground: '#f4f4f6',
            cursor: '#ffffff',
            cursorAccent: '#07080a',
            selectionBackground: 'rgba(255, 255, 255, 0.2)',
            black: '#07080a',
            red: '#ff6161',
            green: '#59d499',
            yellow: '#ffc533',
            blue: '#57c1ff',
            magenta: '#bc8cff',
            cyan: '#57c1ff',
            white: '#f4f4f6',
            brightBlack: '#6a6b6c',
            brightRed: '#ff6161',
            brightGreen: '#59d499',
            brightYellow: '#ffc533',
            brightBlue: '#57c1ff',
            brightMagenta: '#bc8cff',
            brightCyan: '#57c1ff',
            brightWhite: '#ffffff',
        },
    },
    'retro-blue': {
        name: 'retro-blue',
        label: 'Retro CRT Blue',
        cssVars: {
            // Design tokens (Retro CRT Blue palette)
            '--canvas': 'oklch(0.08 0.02 250)',
            '--surface': 'oklch(0.1 0.02 250)',
            '--surface-elevated': 'oklch(0.12 0.02 250)',
            '--surface-card': 'oklch(0.14 0.03 250)',
            '--hairline': 'oklch(0.28 0.08 230)',
            '--hairline-soft': 'oklch(0.28 0.08 230 / 0.5)',
            '--hairline-strong': 'oklch(0.28 0.08 230)',
            '--ink': 'oklch(0.78 0.12 230)',
            '--body-text': 'oklch(0.68 0.1 230)',
            '--mute': 'oklch(0.55 0.08 230)',
            '--ash': 'oklch(0.45 0.06 230)',
            '--stone': 'oklch(0.35 0.04 230)',
            '--on-dark': 'oklch(0.95 0 0)',
            '--on-dark-mute': 'oklch(0.95 0 0 / 0.72)',
            '--accent-blue': 'oklch(0.72 0.15 230)',
            '--accent-blue-soft': 'oklch(0.72 0.15 230 / 0.15)',
            '--accent-red': 'oklch(0.55 0.2 25)',
            '--accent-red-soft': 'oklch(0.55 0.2 25 / 0.15)',
            '--accent-green': 'oklch(0.65 0.15 145)',
            '--accent-green-soft': 'oklch(0.65 0.15 145 / 0.15)',
            '--accent-yellow': 'oklch(0.65 0.15 80)',
            '--accent-yellow-soft': 'oklch(0.65 0.15 80 / 0.15)',
            '--hero-stripe-start': 'oklch(0.55 0.2 25)',
            '--hero-stripe-end': 'oklch(0.4 0.15 25)',
            // Shadcn CSS variable mappings
            '--background': 'var(--canvas)',
            '--foreground': 'var(--ink)',
            '--card': 'var(--surface)',
            '--card-foreground': 'var(--ink)',
            '--popover': 'var(--surface-elevated)',
            '--popover-foreground': 'var(--ink)',
            '--primary': 'oklch(0.72 0.15 230)',
            '--primary-foreground': 'oklch(0.08 0.02 250)',
            '--secondary': 'oklch(0.15 0.03 250)',
            '--secondary-foreground': 'oklch(0.68 0.1 230)',
            '--muted': 'var(--surface-elevated)',
            '--muted-foreground': 'var(--mute)',
            '--accent': 'oklch(0.7 0.15 200)',
            '--accent-foreground': 'oklch(0.08 0.02 250)',
            '--destructive': 'var(--accent-red)',
            '--destructive-foreground': 'var(--on-dark)',
            '--border': 'var(--hairline)',
            '--input': 'var(--surface-elevated)',
            '--ring': 'oklch(0.72 0.15 230)',
            '--success': 'var(--accent-green)',
            '--warning': 'var(--accent-yellow)',
            '--sidebar': 'var(--canvas)',
            '--sidebar-foreground': 'var(--ink)',
            '--sidebar-primary': 'oklch(0.72 0.15 230)',
            '--sidebar-primary-foreground': 'oklch(0.08 0.02 250)',
            '--sidebar-accent': 'oklch(0.15 0.03 250)',
            '--sidebar-accent-foreground': 'var(--ink)',
            '--sidebar-border': 'var(--hairline)',
            '--sidebar-ring': 'oklch(0.72 0.15 230)',
            '--chart-primary': 'oklch(0.72 0.12 230)',
            '--chart-secondary': 'oklch(0.72 0.12 300)',
        },
        xterm: {
            background: '#0a0a1a',
            foreground: '#66b3ff',
            cursor: '#66b3ff',
            cursorAccent: '#0a0a1a',
            selectionBackground: 'rgba(102, 179, 255, 0.25)',
            black: '#1a1a3a',
            red: '#ff7b72',
            green: '#66e088',
            yellow: '#e6c866',
            blue: '#66b3ff',
            magenta: '#c4a0ff',
            cyan: '#66d9e8',
            white: '#b8c4d0',
            brightBlack: '#3a3a5a',
            brightRed: '#ffa198',
            brightGreen: '#7ee8a0',
            brightYellow: '#f0d880',
            brightBlue: '#80c4ff',
            brightMagenta: '#d4b8ff',
            brightCyan: '#80e8f0',
            brightWhite: '#d0dce8',
        },
    },
    'dark': {
        name: 'dark',
        label: 'Dark',
        cssVars: {
            // Design tokens (Dark palette)
            '--canvas': 'oklch(0.1 0 0)',
            '--surface': 'oklch(0.13 0 0)',
            '--surface-elevated': 'oklch(0.15 0 0)',
            '--surface-card': 'oklch(0.17 0 0)',
            '--hairline': 'oklch(0.25 0 0)',
            '--hairline-soft': 'oklch(0.25 0 0 / 0.5)',
            '--hairline-strong': 'oklch(0.25 0 0)',
            '--ink': 'oklch(0.85 0 0)',
            '--body-text': 'oklch(0.7 0 0)',
            '--mute': 'oklch(0.55 0 0)',
            '--ash': 'oklch(0.45 0 0)',
            '--stone': 'oklch(0.35 0 0)',
            '--on-dark': 'oklch(0.95 0 0)',
            '--on-dark-mute': 'oklch(0.95 0 0 / 0.72)',
            '--accent-blue': 'oklch(0.7 0.1 210)',
            '--accent-blue-soft': 'oklch(0.7 0.1 210 / 0.15)',
            '--accent-red': 'oklch(0.55 0.2 25)',
            '--accent-red-soft': 'oklch(0.55 0.2 25 / 0.15)',
            '--accent-green': 'oklch(0.65 0.15 145)',
            '--accent-green-soft': 'oklch(0.65 0.15 145 / 0.15)',
            '--accent-yellow': 'oklch(0.65 0.15 80)',
            '--accent-yellow-soft': 'oklch(0.65 0.15 80 / 0.15)',
            '--hero-stripe-start': 'oklch(0.55 0.2 25)',
            '--hero-stripe-end': 'oklch(0.4 0.15 25)',
            // Shadcn CSS variable mappings
            '--background': 'var(--canvas)',
            '--foreground': 'var(--ink)',
            '--card': 'var(--surface)',
            '--card-foreground': 'var(--ink)',
            '--popover': 'var(--surface-elevated)',
            '--popover-foreground': 'var(--ink)',
            '--primary': 'oklch(0.7 0.1 210)',
            '--primary-foreground': 'oklch(0.1 0 0)',
            '--secondary': 'oklch(0.18 0 0)',
            '--secondary-foreground': 'oklch(0.7 0 0)',
            '--muted': 'var(--surface-elevated)',
            '--muted-foreground': 'var(--mute)',
            '--accent': 'oklch(0.65 0.1 210)',
            '--accent-foreground': 'oklch(0.1 0 0)',
            '--destructive': 'var(--accent-red)',
            '--destructive-foreground': 'var(--on-dark)',
            '--border': 'var(--hairline)',
            '--input': 'var(--surface-elevated)',
            '--ring': 'oklch(0.7 0.1 210)',
            '--success': 'var(--accent-green)',
            '--warning': 'var(--accent-yellow)',
            '--sidebar': 'var(--canvas)',
            '--sidebar-foreground': 'var(--ink)',
            '--sidebar-primary': 'oklch(0.7 0.1 210)',
            '--sidebar-primary-foreground': 'oklch(0.1 0 0)',
            '--sidebar-accent': 'oklch(0.18 0 0)',
            '--sidebar-accent-foreground': 'var(--ink)',
            '--sidebar-border': 'var(--hairline)',
            '--sidebar-ring': 'oklch(0.7 0.1 210)',
            '--chart-primary': 'oklch(0.65 0.1 210)',
            '--chart-secondary': 'oklch(0.65 0.1 310)',
        },
        xterm: {
            background: '#1a1a1a',
            foreground: '#d4d4d4',
            cursor: '#d4d4d4',
            cursorAccent: '#1a1a1a',
            selectionBackground: 'rgba(212, 212, 212, 0.2)',
            black: '#1a1a1a',
            red: '#f44747',
            green: '#6a9955',
            yellow: '#d7ba7d',
            blue: '#569cd6',
            magenta: '#c586c0',
            cyan: '#4ec9b0',
            white: '#d4d4d4',
            brightBlack: '#808080',
            brightRed: '#f44747',
            brightGreen: '#6a9955',
            brightYellow: '#d7ba7d',
            brightBlue: '#569cd6',
            brightMagenta: '#c586c0',
            brightCyan: '#4ec9b0',
            brightWhite: '#e5e5e5',
        },
    },
    'light': {
        name: 'light',
        label: 'Light',
        cssVars: {
            // Design tokens (Light palette)
            '--canvas': 'oklch(0.97 0 0)',
            '--surface': 'oklch(1 0 0)',
            '--surface-elevated': 'oklch(0.94 0 0)',
            '--surface-card': 'oklch(0.92 0 0)',
            '--hairline': 'oklch(0.85 0 0)',
            '--hairline-soft': 'oklch(0.85 0 0 / 0.5)',
            '--hairline-strong': 'oklch(0.85 0 0)',
            '--ink': 'oklch(0.2 0 0)',
            '--body-text': 'oklch(0.35 0 0)',
            '--mute': 'oklch(0.5 0 0)',
            '--ash': 'oklch(0.6 0 0)',
            '--stone': 'oklch(0.7 0 0)',
            '--on-dark': 'oklch(0.2 0 0)',
            '--on-dark-mute': 'oklch(0.2 0 0 / 0.72)',
            '--accent-blue': 'oklch(0.45 0.12 250)',
            '--accent-blue-soft': 'oklch(0.45 0.12 250 / 0.15)',
            '--accent-red': 'oklch(0.5 0.2 25)',
            '--accent-red-soft': 'oklch(0.5 0.2 25 / 0.15)',
            '--accent-green': 'oklch(0.5 0.15 145)',
            '--accent-green-soft': 'oklch(0.5 0.15 145 / 0.15)',
            '--accent-yellow': 'oklch(0.55 0.15 80)',
            '--accent-yellow-soft': 'oklch(0.55 0.15 80 / 0.15)',
            '--hero-stripe-start': 'oklch(0.5 0.2 25)',
            '--hero-stripe-end': 'oklch(0.35 0.15 25)',
            // Shadcn CSS variable mappings
            '--background': 'var(--canvas)',
            '--foreground': 'var(--ink)',
            '--card': 'var(--surface)',
            '--card-foreground': 'var(--ink)',
            '--popover': 'var(--surface-elevated)',
            '--popover-foreground': 'var(--ink)',
            '--primary': 'oklch(0.45 0.12 250)',
            '--primary-foreground': 'oklch(0.98 0 0)',
            '--secondary': 'oklch(0.92 0 0)',
            '--secondary-foreground': 'oklch(0.35 0 0)',
            '--muted': 'var(--surface-elevated)',
            '--muted-foreground': 'var(--mute)',
            '--accent': 'oklch(0.5 0.12 250)',
            '--accent-foreground': 'oklch(0.98 0 0)',
            '--destructive': 'var(--accent-red)',
            '--destructive-foreground': 'var(--on-dark)',
            '--border': 'var(--hairline)',
            '--input': 'var(--surface-elevated)',
            '--ring': 'oklch(0.45 0.12 250)',
            '--success': 'var(--accent-green)',
            '--warning': 'var(--accent-yellow)',
            '--sidebar': 'var(--canvas)',
            '--sidebar-foreground': 'var(--ink)',
            '--sidebar-primary': 'oklch(0.45 0.12 250)',
            '--sidebar-primary-foreground': 'oklch(0.98 0 0)',
            '--sidebar-accent': 'oklch(0.9 0 0)',
            '--sidebar-accent-foreground': 'var(--ink)',
            '--sidebar-border': 'var(--hairline)',
            '--sidebar-ring': 'oklch(0.45 0.12 250)',
            '--chart-primary': 'oklch(0.5 0.12 250)',
            '--chart-secondary': 'oklch(0.5 0.12 310)',
        },
        xterm: {
            background: '#ffffff',
            foreground: '#383a42',
            cursor: '#383a42',
            cursorAccent: '#ffffff',
            selectionBackground: 'rgba(56, 58, 66, 0.15)',
            black: '#383a42',
            red: '#e45649',
            green: '#50a14f',
            yellow: '#c18401',
            blue: '#4078f2',
            magenta: '#a626a4',
            cyan: '#0184bc',
            white: '#fafafa',
            brightBlack: '#a0a1a7',
            brightRed: '#e45649',
            brightGreen: '#50a14f',
            brightYellow: '#c18401',
            brightBlue: '#4078f2',
            brightMagenta: '#a626a4',
            brightCyan: '#0184bc',
            brightWhite: '#ffffff',
        },
    },
    'green-phosphor': {
        name: 'green-phosphor',
        label: 'Green Phosphor',
        cssVars: {
            // Design tokens (Green Phosphor palette)
            '--canvas': 'oklch(0.08 0.02 140)',
            '--surface': 'oklch(0.1 0.02 140)',
            '--surface-elevated': 'oklch(0.12 0.02 140)',
            '--surface-card': 'oklch(0.14 0.03 140)',
            '--hairline': 'oklch(0.25 0.06 145)',
            '--hairline-soft': 'oklch(0.25 0.06 145 / 0.5)',
            '--hairline-strong': 'oklch(0.25 0.06 145)',
            '--ink': 'oklch(0.75 0.15 145)',
            '--body-text': 'oklch(0.65 0.12 145)',
            '--mute': 'oklch(0.5 0.08 145)',
            '--ash': 'oklch(0.4 0.06 145)',
            '--stone': 'oklch(0.3 0.04 145)',
            '--on-dark': 'oklch(0.95 0 0)',
            '--on-dark-mute': 'oklch(0.95 0 0 / 0.72)',
            '--accent-blue': 'oklch(0.65 0.15 200)',
            '--accent-blue-soft': 'oklch(0.65 0.15 200 / 0.15)',
            '--accent-red': 'oklch(0.55 0.2 25)',
            '--accent-red-soft': 'oklch(0.55 0.2 25 / 0.15)',
            '--accent-green': 'oklch(0.65 0.15 145)',
            '--accent-green-soft': 'oklch(0.65 0.15 145 / 0.15)',
            '--accent-yellow': 'oklch(0.65 0.15 80)',
            '--accent-yellow-soft': 'oklch(0.65 0.15 80 / 0.15)',
            '--hero-stripe-start': 'oklch(0.55 0.2 25)',
            '--hero-stripe-end': 'oklch(0.4 0.15 25)',
            // Shadcn CSS variable mappings
            '--background': 'var(--canvas)',
            '--foreground': 'var(--ink)',
            '--card': 'var(--surface)',
            '--card-foreground': 'var(--ink)',
            '--popover': 'var(--surface-elevated)',
            '--popover-foreground': 'var(--ink)',
            '--primary': 'oklch(0.7 0.18 145)',
            '--primary-foreground': 'oklch(0.08 0.02 140)',
            '--secondary': 'oklch(0.15 0.03 140)',
            '--secondary-foreground': 'oklch(0.65 0.12 145)',
            '--muted': 'var(--surface-elevated)',
            '--muted-foreground': 'var(--mute)',
            '--accent': 'oklch(0.65 0.15 145)',
            '--accent-foreground': 'oklch(0.08 0.02 140)',
            '--destructive': 'var(--accent-red)',
            '--destructive-foreground': 'var(--on-dark)',
            '--border': 'var(--hairline)',
            '--input': 'var(--surface-elevated)',
            '--ring': 'oklch(0.7 0.18 145)',
            '--success': 'var(--accent-green)',
            '--warning': 'var(--accent-yellow)',
            '--sidebar': 'var(--canvas)',
            '--sidebar-foreground': 'var(--ink)',
            '--sidebar-primary': 'oklch(0.7 0.18 145)',
            '--sidebar-primary-foreground': 'oklch(0.08 0.02 140)',
            '--sidebar-accent': 'oklch(0.15 0.03 140)',
            '--sidebar-accent-foreground': 'var(--ink)',
            '--sidebar-border': 'var(--hairline)',
            '--sidebar-ring': 'oklch(0.7 0.18 145)',
            '--chart-primary': 'oklch(0.7 0.18 145)',
            '--chart-secondary': 'oklch(0.65 0.15 200)',
        },
        xterm: {
            background: '#0a1a0a',
            foreground: '#33ff33',
            cursor: '#33ff33',
            cursorAccent: '#0a1a0a',
            selectionBackground: 'rgba(51, 255, 51, 0.2)',
            black: '#0a1a0a',
            red: '#ff5555',
            green: '#33ff33',
            yellow: '#ffff55',
            blue: '#55aaff',
            magenta: '#ff55ff',
            cyan: '#55ffff',
            white: '#aaffaa',
            brightBlack: '#225522',
            brightRed: '#ff8888',
            brightGreen: '#66ff66',
            brightYellow: '#ffff88',
            brightBlue: '#88ccff',
            brightMagenta: '#ff88ff',
            brightCyan: '#88ffff',
            brightWhite: '#ccffcc',
        },
    },
    'midnight': {
        name: 'midnight',
        label: 'Midnight',
        cssVars: {
            // Design tokens (Midnight palette)
            '--canvas': 'oklch(0.145 0 0)',
            '--surface': 'oklch(0.205 0 0)',
            '--surface-elevated': 'oklch(0.195 0 0)',
            '--surface-card': 'oklch(0.225 0 0)',
            '--hairline': 'oklch(0.265 0 0)',
            '--hairline-soft': 'oklch(0.265 0 0 / 0.5)',
            '--hairline-strong': 'oklch(0.265 0 0)',
            '--ink': 'oklch(0.922 0 0)',
            '--body-text': 'oklch(0.708 0 0)',
            '--mute': 'oklch(0.556 0 0)',
            '--ash': 'oklch(0.45 0 0)',
            '--stone': 'oklch(0.35 0 0)',
            '--on-dark': 'oklch(0.985 0 0)',
            '--on-dark-mute': 'oklch(0.985 0 0 / 0.72)',
            '--accent-blue': 'oklch(0.623 0.214 259)',
            '--accent-blue-soft': 'oklch(0.623 0.214 259 / 0.15)',
            '--accent-red': 'oklch(0.637 0.237 25)',
            '--accent-red-soft': 'oklch(0.637 0.237 25 / 0.15)',
            '--accent-green': 'oklch(0.685 0.143 175)',
            '--accent-green-soft': 'oklch(0.685 0.143 175 / 0.15)',
            '--accent-yellow': 'oklch(0.768 0.185 70)',
            '--accent-yellow-soft': 'oklch(0.768 0.185 70 / 0.15)',
            '--hero-stripe-start': 'oklch(0.637 0.237 25)',
            '--hero-stripe-end': 'oklch(0.45 0.15 25)',
            // Shadcn CSS variable mappings
            '--background': 'var(--canvas)',
            '--foreground': 'var(--ink)',
            '--card': 'var(--surface)',
            '--card-foreground': 'var(--ink)',
            '--popover': 'var(--surface-elevated)',
            '--popover-foreground': 'var(--ink)',
            '--primary': 'oklch(0.623 0.214 259)',
            '--primary-foreground': 'oklch(0.145 0 0)',
            '--secondary': 'oklch(0.250 0 0)',
            '--secondary-foreground': 'oklch(0.708 0 0)',
            '--muted': 'var(--surface-elevated)',
            '--muted-foreground': 'var(--mute)',
            '--accent': 'oklch(0.685 0.143 175)',
            '--accent-foreground': 'oklch(0.145 0 0)',
            '--destructive': 'var(--accent-red)',
            '--destructive-foreground': 'var(--on-dark)',
            '--border': 'var(--hairline)',
            '--input': 'var(--surface-elevated)',
            '--ring': 'oklch(0.623 0.214 259)',
            '--success': 'var(--accent-green)',
            '--warning': 'var(--accent-yellow)',
            '--sidebar': 'var(--canvas)',
            '--sidebar-foreground': 'var(--ink)',
            '--sidebar-primary': 'oklch(0.623 0.214 259)',
            '--sidebar-primary-foreground': 'oklch(0.145 0 0)',
            '--sidebar-accent': 'oklch(0.250 0 0)',
            '--sidebar-accent-foreground': 'var(--ink)',
            '--sidebar-border': 'var(--hairline)',
            '--sidebar-ring': 'oklch(0.623 0.214 259)',
            '--chart-primary': 'oklch(0.623 0.214 259)',
            '--chart-secondary': 'oklch(0.685 0.143 175)',
        },
        xterm: {
            background: '#0a0a0a',
            foreground: '#e5e5e5',
            cursor: '#3b82f6',
            cursorAccent: '#0a0a0a',
            selectionBackground: 'rgba(59, 130, 246, 0.3)',
            black: '#171717',
            red: '#ef4444',
            green: '#14b8a6',
            yellow: '#f59e0b',
            blue: '#3b82f6',
            magenta: '#a855f7',
            cyan: '#22d3ee',
            white: '#e5e5e5',
            brightBlack: '#737373',
            brightRed: '#f87171',
            brightGreen: '#2dd4bf',
            brightYellow: '#fbbf24',
            brightBlue: '#60a5fa',
            brightMagenta: '#c084fc',
            brightCyan: '#67e8f9',
            brightWhite: '#fafafa',
        },
    }
}

export function applyTheme(themeName: string, customTheme?: Record<string, string>) {
    const theme = themePresets[themeName] || themePresets['raycast']
    const root = document.documentElement
    for (const [key, value] of Object.entries(theme.cssVars)) {
        root.style.setProperty(key, value)
    }
    // Apply custom overrides on top of preset
    if (customTheme) {
        for (const [key, value] of Object.entries(customTheme)) {
            if (value) root.style.setProperty(key, value)
        }
    }
}

export function getXtermTheme(themeName: string) {
    const theme = themePresets[themeName] || themePresets['raycast']
    return theme.xterm
}
